name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build code
        run: |
          go build ./cmd/...

      - name: Check API with invalid API key (and invalid PDF)
        env:
          PDFTABLES_API_KEY: ${{ secrets.PDFTABLES_API_KEY }}
        run: |
          ./pdftables-api 2>&1 README.md | grep "unauthorized"
